def seed_exercises(db):
    """Seed the exercise taxonomy database with 250+ exercises."""
    count = db.execute("SELECT COUNT(*) FROM exercises").fetchone()[0]
    if count > 0:
        return

    exercises = [
        # === COMPOUND BARBELL - HORIZONTAL PUSH ===
        ("Barbell Bench Press", "compound", "horizontal_push", "chest,anterior_deltoid,triceps", "serratus_anterior", "barbell", 1, 2, 4, 6, 22),
        ("Close-Grip Bench Press", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "barbell", 1, 2, 3, 6, 20),
        ("Wide-Grip Bench Press", "compound", "horizontal_push", "chest,anterior_deltoid", "triceps", "barbell", 1, 3, 4, 6, 20),
        ("Paused Bench Press", "compound", "horizontal_push", "chest,anterior_deltoid,triceps", "serratus_anterior", "barbell", 1, 3, 4, 6, 20),
        ("Spoto Press", "compound", "horizontal_push", "chest,triceps", "anterior_deltoid", "barbell", 1, 3, 4, 6, 18),
        ("Floor Press", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "barbell", 1, 2, 3, 6, 18),
        ("Larsen Press", "compound", "horizontal_push", "chest,anterior_deltoid,triceps", "core", "barbell", 1, 3, 4, 6, 18),
        ("Board Press", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "barbell", 1, 3, 3, 6, 18),
        ("Incline Barbell Press", "compound", "horizontal_push", "upper_chest,anterior_deltoid,triceps", "serratus_anterior", "barbell", 1, 2, 4, 6, 20),
        ("Decline Barbell Press", "compound", "horizontal_push", "lower_chest,triceps", "anterior_deltoid", "barbell", 1, 2, 3, 6, 18),

        # === COMPOUND BARBELL - VERTICAL PUSH ===
        ("Overhead Press", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "upper_chest,core", "barbell", 1, 2, 4, 6, 18),
        ("Push Press", "compound", "vertical_push", "anterior_deltoid,triceps", "quads,glutes,core", "barbell", 1, 3, 4, 6, 16),
        ("Behind-the-Neck Press", "compound", "vertical_push", "lateral_deltoid,anterior_deltoid,triceps", "upper_traps", "barbell", 1, 4, 4, 4, 14),
        ("Z-Press", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "core", "barbell", 1, 4, 4, 6, 16),
        ("Pin Press (Overhead)", "compound", "vertical_push", "anterior_deltoid,triceps", "lateral_deltoid", "barbell", 1, 3, 3, 6, 16),
        ("Viking Press", "compound", "vertical_push", "anterior_deltoid,triceps", "lateral_deltoid,core", "machine", 1, 2, 3, 6, 18),
        ("Barbell Thruster", "compound", "vertical_push", "quads,anterior_deltoid,triceps", "glutes,core", "barbell", 1, 3, 5, 6, 16),
        ("Strict Press (Military)", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "core,upper_chest", "barbell", 1, 2, 4, 6, 18),

        # === COMPOUND BARBELL - SQUAT PATTERN ===
        ("Back Squat", "compound", "squat", "quads,glutes", "hamstrings,erectors,core", "barbell", 1, 2, 5, 6, 20),
        ("Front Squat", "compound", "squat", "quads,core", "glutes,upper_back", "barbell", 1, 3, 5, 6, 18),
        ("Safety Bar Squat", "compound", "squat", "quads,glutes", "hamstrings,upper_back,core", "barbell", 1, 2, 4, 6, 20),
        ("Paused Back Squat", "compound", "squat", "quads,glutes", "hamstrings,core", "barbell", 1, 3, 5, 6, 18),
        ("Pin Squat", "compound", "squat", "quads,glutes", "hamstrings,core", "barbell", 1, 3, 4, 6, 16),
        ("Box Squat", "compound", "squat", "quads,glutes,hamstrings", "core,erectors", "barbell", 1, 3, 4, 6, 18),
        ("Tempo Squat", "compound", "squat", "quads,glutes", "hamstrings,core", "barbell", 1, 3, 5, 6, 18),
        ("Anderson Squat", "compound", "squat", "quads,glutes", "core,erectors", "barbell", 1, 4, 4, 6, 16),
        ("Zercher Squat", "compound", "squat", "quads,glutes,core", "biceps,upper_back", "barbell", 1, 4, 5, 6, 16),
        ("Overhead Squat", "compound", "squat", "quads,glutes,core", "shoulders,upper_back", "barbell", 1, 5, 4, 4, 14),

        # === COMPOUND BARBELL - HIP HINGE ===
        ("Conventional Deadlift", "compound", "hip_hinge", "hamstrings,glutes,erectors", "quads,lats,traps,forearms", "barbell", 1, 2, 5, 4, 16),
        ("Sumo Deadlift", "compound", "hip_hinge", "glutes,quads,hamstrings", "erectors,adductors", "barbell", 1, 3, 5, 4, 16),
        ("Romanian Deadlift", "compound", "hip_hinge", "hamstrings,glutes", "erectors,core", "barbell", 1, 2, 3, 6, 18),
        ("Stiff-Leg Deadlift", "compound", "hip_hinge", "hamstrings,glutes,erectors", "core", "barbell", 1, 2, 4, 6, 18),
        ("Deficit Deadlift", "compound", "hip_hinge", "hamstrings,glutes,quads", "erectors,lats", "barbell", 1, 3, 5, 4, 16),
        ("Block Pull / Rack Pull", "compound", "hip_hinge", "erectors,glutes,traps", "hamstrings,lats", "barbell", 1, 3, 4, 4, 16),
        ("Trap Bar Deadlift", "compound", "hip_hinge", "quads,glutes,hamstrings", "erectors,traps", "barbell", 1, 2, 4, 6, 18),
        ("Paused Deadlift", "compound", "hip_hinge", "hamstrings,glutes,erectors", "quads,lats", "barbell", 1, 3, 5, 4, 16),
        ("Snatch-Grip Deadlift", "compound", "hip_hinge", "upper_back,hamstrings,glutes", "erectors,traps", "barbell", 1, 4, 5, 4, 16),
        ("Good Morning", "compound", "hip_hinge", "hamstrings,erectors,glutes", "core", "barbell", 1, 3, 4, 6, 16),
        ("Seated Good Morning", "compound", "hip_hinge", "hamstrings,erectors", "glutes,core", "barbell", 1, 3, 3, 6, 14),

        # === COMPOUND - HORIZONTAL PULL ===
        ("Barbell Row (Bent-Over)", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps,erectors", "barbell", 1, 2, 3, 6, 20),
        ("Pendlay Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps,erectors", "barbell", 1, 3, 4, 6, 18),
        ("Seal Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps", "barbell", 1, 2, 2, 6, 20),
        ("T-Bar Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps,erectors", "barbell", 1, 2, 3, 6, 20),
        ("Meadows Row", "compound", "horizontal_pull", "lats,rear_deltoid", "biceps,rhomboids", "barbell", 0, 3, 3, 6, 18),
        ("Chest-Supported Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps", "dumbbell", 1, 1, 2, 6, 22),
        ("Kroc Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,forearms,rear_deltoid", "dumbbell", 0, 2, 3, 6, 18),
        ("Cable Row (Seated)", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid", "cable", 1, 1, 2, 6, 22),
        ("Single-Arm Cable Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid,core", "cable", 0, 2, 2, 6, 20),
        ("Machine Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid", "machine", 1, 1, 2, 6, 22),
        ("Helms Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps", "dumbbell", 1, 2, 2, 6, 20),

        # === COMPOUND - VERTICAL PULL ===
        ("Pull-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids,rear_deltoid,forearms", "bodyweight", 1, 2, 3, 6, 20),
        ("Chin-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids,forearms", "bodyweight", 1, 2, 3, 6, 20),
        ("Neutral-Grip Pull-Up", "compound", "vertical_pull", "lats,biceps,brachialis", "rhomboids,rear_deltoid", "bodyweight", 1, 2, 3, 6, 20),
        ("Weighted Pull-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids,rear_deltoid,forearms", "bodyweight", 1, 3, 4, 6, 18),
        ("Weighted Chin-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids,forearms", "bodyweight", 1, 3, 4, 6, 18),
        ("Lat Pulldown", "compound", "vertical_pull", "lats,biceps", "rhomboids,rear_deltoid", "cable", 1, 1, 2, 6, 22),
        ("Close-Grip Lat Pulldown", "compound", "vertical_pull", "lats,biceps,brachialis", "rhomboids", "cable", 1, 1, 2, 6, 22),
        ("Wide-Grip Lat Pulldown", "compound", "vertical_pull", "lats,rear_deltoid", "biceps,rhomboids", "cable", 1, 1, 2, 6, 22),
        ("Behind-the-Neck Lat Pulldown", "compound", "vertical_pull", "lats,rear_deltoid,rhomboids", "biceps", "cable", 1, 2, 2, 6, 18),
        ("Single-Arm Lat Pulldown", "compound", "vertical_pull", "lats", "biceps,rear_deltoid", "cable", 0, 2, 2, 6, 20),
        ("Assisted Pull-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids,rear_deltoid", "machine", 1, 1, 2, 6, 22),
        ("One-Arm Chin-Up (OAC)", "compound", "vertical_pull", "lats,biceps", "forearms,core,rear_deltoid", "bodyweight", 0, 5, 5, 4, 12),
        ("1.25 Neutral Chin-Up", "compound", "vertical_pull", "lats,biceps,brachialis", "rhomboids", "bodyweight", 1, 4, 4, 6, 16),
        ("Pulley-Assisted OAC", "compound", "vertical_pull", "lats,biceps", "forearms,core", "cable", 0, 5, 4, 4, 14),

        # === DUMBBELL - PUSH ===
        ("Dumbbell Bench Press", "compound", "horizontal_push", "chest,anterior_deltoid,triceps", "serratus_anterior", "dumbbell", 1, 1, 3, 6, 22),
        ("Incline Dumbbell Press", "compound", "horizontal_push", "upper_chest,anterior_deltoid", "triceps", "dumbbell", 1, 1, 3, 6, 22),
        ("Decline Dumbbell Press", "compound", "horizontal_push", "lower_chest,triceps", "anterior_deltoid", "dumbbell", 1, 1, 3, 6, 20),
        ("Dumbbell Overhead Press", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "core", "dumbbell", 1, 2, 3, 6, 20),
        ("Seated Dumbbell Press", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "", "dumbbell", 1, 1, 3, 6, 20),
        ("Arnold Press", "compound", "vertical_push", "anterior_deltoid,lateral_deltoid,triceps", "upper_chest", "dumbbell", 1, 2, 3, 6, 18),
        ("Dumbbell Floor Press", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "dumbbell", 1, 1, 3, 6, 18),
        ("Incline Smith Machine Press", "compound", "horizontal_push", "upper_chest,anterior_deltoid,triceps", "", "machine", 1, 1, 3, 6, 22),
        ("Range Press", "compound", "horizontal_push", "chest,anterior_deltoid", "triceps", "dumbbell", 1, 3, 3, 6, 18),
        ("JM Press", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "barbell", 1, 3, 3, 6, 16),

        # === DUMBBELL - LOWER ===
        ("Dumbbell Goblet Squat", "compound", "squat", "quads,glutes", "core", "dumbbell", 1, 1, 2, 6, 20),
        ("Dumbbell Lunge", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 1, 3, 6, 20),
        ("Dumbbell Romanian Deadlift", "compound", "hip_hinge", "hamstrings,glutes", "erectors", "dumbbell", 1, 1, 3, 6, 20),
        ("Dumbbell Step-Up", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 2, 3, 6, 18),
        ("Dumbbell Split Squat", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 2, 3, 6, 18),
        ("Dumbbell Bulgarian Split Squat", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 2, 4, 6, 18),
        ("Goblet Cyclic Squat", "compound", "squat", "quads,glutes", "core,calves", "dumbbell", 1, 2, 3, 6, 18),

        # === BARBELL - LUNGE / UNILATERAL ===
        ("Barbell Walking Lunge", "compound", "lunge", "quads,glutes", "hamstrings,core", "barbell", 0, 2, 4, 6, 18),
        ("Barbell Reverse Lunge", "compound", "lunge", "quads,glutes", "hamstrings,core", "barbell", 0, 2, 3, 6, 18),
        ("Barbell Bulgarian Split Squat", "compound", "lunge", "quads,glutes", "hamstrings,core", "barbell", 0, 3, 4, 6, 16),
        ("Zercher Reverse Lunge", "compound", "lunge", "quads,glutes,core", "hamstrings,biceps", "barbell", 0, 4, 4, 6, 16),
        ("Barbell Step-Up", "compound", "lunge", "quads,glutes", "hamstrings", "barbell", 0, 2, 3, 6, 18),
        ("Front Foot Elevated Split Squat", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 2, 3, 6, 18),
        ("Kickstand RDL", "compound", "hip_hinge", "hamstrings,glutes", "erectors,core", "dumbbell", 0, 2, 3, 6, 18),
        ("Single-Leg RDL", "compound", "hip_hinge", "hamstrings,glutes", "erectors,core", "dumbbell", 0, 3, 3, 6, 16),
        ("Smith Machine Pistol Squat", "compound", "squat", "quads,glutes", "core", "machine", 0, 3, 3, 6, 16),

        # === MACHINE - LOWER ===
        ("Leg Press", "compound", "squat", "quads,glutes", "hamstrings", "machine", 1, 1, 3, 6, 22),
        ("Hack Squat", "compound", "squat", "quads,glutes", "hamstrings", "machine", 1, 1, 3, 6, 22),
        ("Belt Squat", "compound", "squat", "quads,glutes", "core", "machine", 1, 1, 3, 6, 22),
        ("Pendulum Squat", "compound", "squat", "quads,glutes", "", "machine", 1, 1, 3, 6, 22),
        ("Smith Machine Squat", "compound", "squat", "quads,glutes", "hamstrings", "machine", 1, 1, 3, 6, 22),
        ("V-Squat", "compound", "squat", "quads,glutes", "hamstrings", "machine", 1, 1, 3, 6, 22),

        # === ISOLATION - QUADS ===
        ("Leg Extension", "isolation", "knee_extension", "quads", "", "machine", 1, 1, 1, 8, 24),
        ("Single-Leg Extension", "isolation", "knee_extension", "quads", "", "machine", 0, 1, 1, 8, 24),
        ("Sissy Squat", "isolation", "knee_extension", "quads", "core", "bodyweight", 1, 3, 2, 6, 18),
        ("Reverse Nordic Curl", "isolation", "knee_extension", "quads", "", "bodyweight", 1, 3, 2, 6, 16),
        ("Spanish Squat", "isolation", "knee_extension", "quads", "", "band", 1, 2, 2, 8, 20),

        # === ISOLATION - HAMSTRINGS ===
        ("Lying Leg Curl", "isolation", "knee_flexion", "hamstrings", "", "machine", 1, 1, 1, 8, 24),
        ("Seated Leg Curl", "isolation", "knee_flexion", "hamstrings", "", "machine", 1, 1, 1, 8, 24),
        ("Nordic Curl", "isolation", "knee_flexion", "hamstrings", "", "bodyweight", 1, 4, 4, 6, 16),
        ("Razor Curl", "isolation", "knee_flexion", "hamstrings", "", "bodyweight", 1, 3, 3, 6, 18),
        ("Glute-Ham Raise", "compound", "knee_flexion", "hamstrings,glutes", "erectors", "bodyweight", 1, 3, 3, 6, 18),
        ("Slider Leg Curl", "isolation", "knee_flexion", "hamstrings", "glutes", "bodyweight", 1, 2, 2, 8, 20),
        ("Single-Leg Lying Curl", "isolation", "knee_flexion", "hamstrings", "", "machine", 0, 1, 1, 8, 24),
        ("Standing Leg Curl", "isolation", "knee_flexion", "hamstrings", "", "machine", 0, 1, 1, 8, 24),

        # === ISOLATION - GLUTES ===
        ("Hip Thrust", "compound", "hip_extension", "glutes", "hamstrings", "barbell", 1, 2, 3, 6, 20),
        ("Single-Leg Hip Thrust", "compound", "hip_extension", "glutes", "hamstrings,core", "bodyweight", 0, 2, 2, 6, 20),
        ("Barbell Glute Bridge", "compound", "hip_extension", "glutes", "hamstrings", "barbell", 1, 1, 2, 6, 22),
        ("Cable Pull-Through", "compound", "hip_extension", "glutes,hamstrings", "erectors", "cable", 1, 1, 2, 8, 22),
        ("Hip Abduction Machine", "isolation", "hip_abduction", "glute_medius,glute_minimus", "", "machine", 1, 1, 1, 8, 24),
        ("Cable Kickback", "isolation", "hip_extension", "glutes", "", "cable", 0, 1, 1, 8, 22),
        ("Frog Pump", "isolation", "hip_extension", "glutes", "", "bodyweight", 1, 1, 1, 8, 22),
        ("Reverse Hyperextension", "compound", "hip_extension", "glutes,hamstrings,erectors", "", "machine", 1, 1, 2, 8, 22),
        ("45-Degree Back Extension", "compound", "hip_extension", "erectors,glutes,hamstrings", "", "bodyweight", 1, 1, 2, 8, 22),

        # === ISOLATION - CHEST ===
        ("Cable Fly (Mid)", "isolation", "horizontal_push", "chest", "anterior_deltoid", "cable", 1, 1, 1, 8, 24),
        ("Cable Fly (Low-to-High)", "isolation", "horizontal_push", "upper_chest", "anterior_deltoid", "cable", 1, 1, 1, 8, 24),
        ("Cable Fly (High-to-Low)", "isolation", "horizontal_push", "lower_chest", "anterior_deltoid", "cable", 1, 1, 1, 8, 24),
        ("Dumbbell Fly", "isolation", "horizontal_push", "chest", "anterior_deltoid", "dumbbell", 1, 1, 2, 8, 22),
        ("Incline Dumbbell Fly", "isolation", "horizontal_push", "upper_chest", "anterior_deltoid", "dumbbell", 1, 1, 2, 8, 22),
        ("Pec Deck", "isolation", "horizontal_push", "chest", "anterior_deltoid", "machine", 1, 1, 1, 8, 24),
        ("Machine Chest Press", "compound", "horizontal_push", "chest,anterior_deltoid,triceps", "", "machine", 1, 1, 2, 6, 22),
        ("Machine Incline Press", "compound", "horizontal_push", "upper_chest,anterior_deltoid", "triceps", "machine", 1, 1, 2, 6, 22),

        # === ISOLATION - SHOULDERS ===
        ("Lateral Raise (Dumbbell)", "isolation", "lateral_raise", "lateral_deltoid", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Cable Lateral Raise", "isolation", "lateral_raise", "lateral_deltoid", "", "cable", 0, 1, 1, 10, 25),
        ("Machine Lateral Raise", "isolation", "lateral_raise", "lateral_deltoid", "", "machine", 1, 1, 1, 10, 25),
        ("Leaning Lateral Raise", "isolation", "lateral_raise", "lateral_deltoid", "", "dumbbell", 0, 2, 1, 10, 25),
        ("Upright Row", "compound", "lateral_raise", "lateral_deltoid,upper_traps", "anterior_deltoid,biceps", "barbell", 1, 2, 2, 8, 20),
        ("Cable Upright Row", "compound", "lateral_raise", "lateral_deltoid,upper_traps", "anterior_deltoid", "cable", 1, 2, 2, 8, 20),
        ("Face Pull", "isolation", "horizontal_pull", "rear_deltoid,rhomboids", "external_rotators", "cable", 1, 1, 1, 10, 25),
        ("Reverse Pec Deck", "isolation", "horizontal_pull", "rear_deltoid", "rhomboids", "machine", 1, 1, 1, 10, 25),
        ("Rear Delt Fly (Dumbbell)", "isolation", "horizontal_pull", "rear_deltoid", "rhomboids", "dumbbell", 1, 1, 1, 10, 25),
        ("Cable Rear Delt Fly", "isolation", "horizontal_pull", "rear_deltoid", "rhomboids", "cable", 1, 1, 1, 10, 25),
        ("Band Pull-Apart", "isolation", "horizontal_pull", "rear_deltoid,rhomboids", "external_rotators", "band", 1, 1, 1, 10, 25),
        ("Lu Raise", "isolation", "lateral_raise", "lateral_deltoid,anterior_deltoid", "", "dumbbell", 1, 3, 2, 8, 18),
        ("Y-Raise", "isolation", "vertical_push", "lower_traps,rear_deltoid", "", "dumbbell", 1, 1, 1, 10, 25),

        # === ISOLATION - TRICEPS ===
        ("Tricep Pushdown (Rope)", "isolation", "elbow_extension", "triceps", "", "cable", 1, 1, 1, 10, 25),
        ("Tricep Pushdown (Bar)", "isolation", "elbow_extension", "triceps", "", "cable", 1, 1, 1, 10, 25),
        ("Overhead Tricep Extension (Cable)", "isolation", "elbow_extension", "triceps_long_head", "", "cable", 1, 1, 1, 10, 25),
        ("Overhead Tricep Extension (Dumbbell)", "isolation", "elbow_extension", "triceps_long_head", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Skull Crusher", "isolation", "elbow_extension", "triceps", "", "barbell", 1, 2, 2, 8, 22),
        ("Dumbbell Skull Crusher", "isolation", "elbow_extension", "triceps", "", "dumbbell", 1, 2, 2, 8, 22),
        ("Dip", "compound", "vertical_push", "triceps,chest,anterior_deltoid", "", "bodyweight", 1, 2, 3, 6, 20),
        ("Weighted Dip", "compound", "vertical_push", "triceps,chest,anterior_deltoid", "", "bodyweight", 1, 3, 4, 6, 18),
        ("Kickback (Cable)", "isolation", "elbow_extension", "triceps", "", "cable", 0, 1, 1, 10, 25),
        ("Diamond Push-Up", "compound", "horizontal_push", "triceps,chest", "anterior_deltoid", "bodyweight", 1, 2, 2, 8, 20),
        ("French Press", "isolation", "elbow_extension", "triceps_long_head", "", "barbell", 1, 2, 2, 8, 22),
        ("Butcher Block Tricep Extension", "isolation", "elbow_extension", "triceps", "", "dumbbell", 1, 2, 2, 8, 20),

        # === ISOLATION - BICEPS ===
        ("Barbell Curl", "isolation", "elbow_flexion", "biceps", "brachialis,forearms", "barbell", 1, 1, 1, 10, 25),
        ("EZ-Bar Curl", "isolation", "elbow_flexion", "biceps", "brachialis", "barbell", 1, 1, 1, 10, 25),
        ("Dumbbell Curl", "isolation", "elbow_flexion", "biceps", "brachialis", "dumbbell", 1, 1, 1, 10, 25),
        ("Alternating Dumbbell Curl", "isolation", "elbow_flexion", "biceps", "brachialis", "dumbbell", 0, 1, 1, 10, 25),
        ("Seated Alternating DB Curl", "isolation", "elbow_flexion", "biceps", "brachialis", "dumbbell", 0, 1, 1, 10, 25),
        ("Incline Dumbbell Curl", "isolation", "elbow_flexion", "biceps_long_head", "brachialis", "dumbbell", 1, 1, 1, 10, 25),
        ("Hammer Curl", "isolation", "elbow_flexion", "brachialis,biceps", "forearms", "dumbbell", 1, 1, 1, 10, 25),
        ("Cable Curl", "isolation", "elbow_flexion", "biceps", "brachialis", "cable", 1, 1, 1, 10, 25),
        ("High Cable Curl", "isolation", "elbow_flexion", "biceps", "", "cable", 0, 1, 1, 10, 25),
        ("Preacher Curl", "isolation", "elbow_flexion", "biceps_short_head", "brachialis", "barbell", 1, 1, 1, 10, 25),
        ("Concentration Curl", "isolation", "elbow_flexion", "biceps", "", "dumbbell", 0, 1, 1, 10, 25),
        ("Spider Curl", "isolation", "elbow_flexion", "biceps_short_head", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Reverse Curl", "isolation", "elbow_flexion", "brachioradialis,brachialis", "biceps", "barbell", 1, 1, 1, 10, 25),
        ("Bayesian Curl", "isolation", "elbow_flexion", "biceps_long_head", "", "cable", 0, 2, 1, 10, 25),

        # === ISOLATION - CALVES ===
        ("Standing Calf Raise (Machine)", "isolation", "ankle_plantar_flexion", "gastrocnemius", "soleus", "machine", 1, 1, 1, 10, 25),
        ("Seated Calf Raise", "isolation", "ankle_plantar_flexion", "soleus", "gastrocnemius", "machine", 1, 1, 1, 10, 25),
        ("Leg Press Calf Raise", "isolation", "ankle_plantar_flexion", "gastrocnemius,soleus", "", "machine", 1, 1, 1, 10, 25),
        ("Single-Leg Calf Raise", "isolation", "ankle_plantar_flexion", "gastrocnemius,soleus", "", "bodyweight", 0, 1, 1, 10, 25),
        ("Donkey Calf Raise", "isolation", "ankle_plantar_flexion", "gastrocnemius", "soleus", "machine", 1, 1, 1, 10, 25),
        ("Smith Machine Calf Raise", "isolation", "ankle_plantar_flexion", "gastrocnemius,soleus", "", "machine", 1, 1, 1, 10, 25),

        # === CORE / ABS ===
        ("Hanging Leg Raise", "isolation", "spinal_flexion", "rectus_abdominis,hip_flexors", "obliques", "bodyweight", 1, 2, 2, 8, 22),
        ("Hanging Knee Raise", "isolation", "spinal_flexion", "rectus_abdominis,hip_flexors", "obliques", "bodyweight", 1, 1, 2, 8, 22),
        ("Cable Crunch", "isolation", "spinal_flexion", "rectus_abdominis", "obliques", "cable", 1, 1, 1, 10, 25),
        ("Ab Wheel Rollout", "isolation", "anti_extension", "rectus_abdominis,core", "lats,shoulders", "bodyweight", 1, 3, 3, 8, 20),
        ("Pallof Press", "isolation", "anti_rotation", "obliques,core", "", "cable", 0, 1, 1, 10, 25),
        ("Dragon Flag", "isolation", "anti_extension", "rectus_abdominis,core", "", "bodyweight", 1, 4, 3, 6, 16),
        ("Decline Sit-Up", "isolation", "spinal_flexion", "rectus_abdominis", "hip_flexors", "bodyweight", 1, 1, 2, 10, 22),
        ("Weighted Decline Sit-Up", "isolation", "spinal_flexion", "rectus_abdominis", "hip_flexors", "bodyweight", 1, 2, 2, 10, 22),
        ("Plank", "isolation", "anti_extension", "core,rectus_abdominis", "obliques", "bodyweight", 1, 1, 1, 10, 25),
        ("Side Plank", "isolation", "anti_lateral_flexion", "obliques,core", "", "bodyweight", 0, 1, 1, 10, 25),
        ("Copenhagen Plank", "isolation", "anti_lateral_flexion", "obliques,adductors", "core", "bodyweight", 0, 3, 2, 8, 18),
        ("Copenhagen Dip", "isolation", "anti_lateral_flexion", "adductors,obliques", "core", "bodyweight", 0, 3, 2, 8, 18),
        ("Incline Side Bend", "isolation", "lateral_flexion", "obliques", "core", "bodyweight", 0, 1, 1, 10, 25),
        ("Woodchop (Cable)", "isolation", "rotation", "obliques,core", "", "cable", 0, 1, 1, 10, 25),
        ("Dead Bug", "isolation", "anti_extension", "core,rectus_abdominis", "hip_flexors", "bodyweight", 1, 1, 1, 10, 25),
        ("Bird Dog", "isolation", "anti_extension", "core,erectors", "glutes", "bodyweight", 0, 1, 1, 10, 25),
        ("L-Sit Hold", "isolation", "anti_extension", "core,hip_flexors", "rectus_abdominis", "bodyweight", 1, 3, 2, 6, 18),
        ("GHD Sit-Up", "isolation", "spinal_flexion", "rectus_abdominis,hip_flexors", "", "machine", 1, 2, 2, 8, 20),
        ("Suitcase Carry", "compound", "anti_lateral_flexion", "obliques,core,forearms", "traps", "dumbbell", 0, 1, 2, 8, 22),
        ("Farmer Carry", "compound", "loaded_carry", "forearms,traps,core", "erectors", "dumbbell", 1, 1, 2, 8, 22),

        # === TRAPS / UPPER BACK ===
        ("Barbell Shrug", "isolation", "scapular_elevation", "upper_traps", "", "barbell", 1, 1, 1, 10, 25),
        ("Dumbbell Shrug", "isolation", "scapular_elevation", "upper_traps", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Trap Bar Shrug", "isolation", "scapular_elevation", "upper_traps", "", "barbell", 1, 1, 1, 10, 25),
        ("Cable Shrug", "isolation", "scapular_elevation", "upper_traps", "", "cable", 1, 1, 1, 10, 25),
        ("Snatch-Grip High Pull", "compound", "scapular_elevation", "upper_traps,rear_deltoid", "erectors,biceps", "barbell", 1, 4, 4, 6, 16),

        # === FOREARMS / GRIP ===
        ("Wrist Curl (Barbell)", "isolation", "wrist_flexion", "forearm_flexors", "", "barbell", 1, 1, 1, 12, 25),
        ("Reverse Wrist Curl", "isolation", "wrist_extension", "forearm_extensors", "", "barbell", 1, 1, 1, 12, 25),
        ("Plate Pinch Hold", "isolation", "grip", "forearms", "", "other", 1, 1, 1, 8, 25),
        ("Fat Grip Curl", "isolation", "elbow_flexion", "biceps,forearms", "", "dumbbell", 1, 2, 2, 10, 22),
        ("Dead Hang", "isolation", "grip", "forearms,lats", "", "bodyweight", 1, 1, 1, 8, 25),

        # === OLYMPIC LIFTING / POWER ===
        ("Power Clean", "compound", "olympic", "quads,glutes,hamstrings,traps", "erectors,shoulders,core", "barbell", 1, 5, 5, 4, 14),
        ("Hang Clean", "compound", "olympic", "quads,glutes,traps", "hamstrings,core", "barbell", 1, 4, 5, 4, 14),
        ("Clean & Jerk", "compound", "olympic", "quads,glutes,hamstrings,shoulders,traps", "core,triceps", "barbell", 1, 5, 5, 4, 12),
        ("Power Snatch", "compound", "olympic", "quads,glutes,hamstrings,traps,shoulders", "core,erectors", "barbell", 1, 5, 5, 4, 12),
        ("Hang Snatch", "compound", "olympic", "quads,glutes,traps,shoulders", "core", "barbell", 1, 5, 5, 4, 12),
        ("Clean Pull", "compound", "olympic", "hamstrings,glutes,erectors,traps", "quads", "barbell", 1, 4, 4, 4, 16),
        ("Snatch Pull", "compound", "olympic", "hamstrings,glutes,erectors,traps", "quads", "barbell", 1, 4, 4, 4, 16),
        ("Muscle Snatch", "compound", "olympic", "traps,shoulders,triceps", "erectors,core", "barbell", 1, 4, 4, 4, 14),

        # === PLYOMETRICS / POWER ===
        ("Box Jump", "compound", "plyometric", "quads,glutes", "calves,core", "bodyweight", 1, 2, 3, 6, 18),
        ("Depth Jump", "compound", "plyometric", "quads,glutes,calves", "core", "bodyweight", 1, 4, 4, 4, 14),
        ("Kneeling Jump", "compound", "plyometric", "quads,glutes,hip_flexors", "core", "bodyweight", 1, 3, 3, 6, 16),
        ("Broad Jump", "compound", "plyometric", "quads,glutes", "hamstrings,calves", "bodyweight", 1, 2, 3, 6, 18),
        ("Plyo Push-Up", "compound", "plyometric", "chest,triceps", "anterior_deltoid", "bodyweight", 1, 3, 3, 6, 16),
        ("Medicine Ball Slam", "compound", "plyometric", "lats,core,anterior_deltoid", "triceps", "other", 1, 2, 3, 8, 18),
        ("Kettlebell Swing", "compound", "hip_hinge", "glutes,hamstrings", "core,erectors", "kettlebell", 1, 2, 3, 8, 20),
        ("Kettlebell Clean", "compound", "olympic", "glutes,hamstrings,forearms", "core,shoulders", "kettlebell", 0, 3, 3, 6, 18),

        # === BODYWEIGHT ===
        ("Push-Up", "compound", "horizontal_push", "chest,triceps,anterior_deltoid", "core", "bodyweight", 1, 1, 1, 10, 25),
        ("Pike Push-Up", "compound", "vertical_push", "anterior_deltoid,triceps", "upper_chest", "bodyweight", 1, 2, 2, 8, 22),
        ("Handstand Push-Up", "compound", "vertical_push", "anterior_deltoid,triceps", "traps,core", "bodyweight", 1, 4, 4, 4, 14),
        ("Inverted Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps,core", "bodyweight", 1, 1, 2, 8, 22),
        ("Ring Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid,core", "bodyweight", 1, 2, 2, 8, 20),
        ("Ring Dip", "compound", "vertical_push", "chest,triceps,anterior_deltoid", "core", "bodyweight", 1, 3, 4, 6, 16),
        ("Muscle-Up", "compound", "vertical_pull", "lats,chest,triceps", "biceps,core", "bodyweight", 1, 5, 5, 4, 12),
        ("Pistol Squat", "compound", "squat", "quads,glutes", "core,hip_flexors", "bodyweight", 0, 3, 3, 6, 16),
        ("Archer Push-Up", "compound", "horizontal_push", "chest,triceps", "anterior_deltoid,core", "bodyweight", 0, 3, 2, 8, 18),
        ("Ring Push-Up", "compound", "horizontal_push", "chest,triceps,anterior_deltoid", "core", "bodyweight", 1, 2, 2, 8, 20),

        # === MACHINE - UPPER ===
        ("Machine Shoulder Press", "compound", "vertical_push", "anterior_deltoid,triceps", "lateral_deltoid", "machine", 1, 1, 2, 6, 22),
        ("Cable Pullover", "isolation", "vertical_pull", "lats", "chest,triceps_long_head", "cable", 1, 1, 1, 8, 24),
        ("Machine Pullover", "isolation", "vertical_pull", "lats", "chest", "machine", 1, 1, 1, 8, 24),
        ("Machine Bicep Curl", "isolation", "elbow_flexion", "biceps", "", "machine", 1, 1, 1, 10, 25),
        ("Machine Tricep Extension", "isolation", "elbow_extension", "triceps", "", "machine", 1, 1, 1, 10, 25),
        ("Machine Rear Delt Fly", "isolation", "horizontal_pull", "rear_deltoid", "rhomboids", "machine", 1, 1, 1, 10, 25),

        # === MOBILITY / PREHAB ===
        ("T-Spine Pull-Over", "isolation", "thoracic_extension", "lats,chest", "core", "dumbbell", 1, 1, 1, 10, 25),
        ("Kneeling T-Spine Rotation", "isolation", "thoracic_rotation", "obliques,core", "erectors", "bodyweight", 0, 1, 1, 10, 25),
        ("Band Dislocate", "isolation", "shoulder_mobility", "rotator_cuff,rear_deltoid", "", "band", 1, 1, 1, 10, 25),
        ("External Rotation (Cable)", "isolation", "shoulder_mobility", "external_rotators", "", "cable", 0, 1, 1, 10, 25),
        ("Internal Rotation (Cable)", "isolation", "shoulder_mobility", "internal_rotators", "", "cable", 0, 1, 1, 10, 25),
        ("Hip 90/90 Stretch", "isolation", "hip_mobility", "hip_flexors,glutes", "", "bodyweight", 0, 1, 1, 10, 25),
        ("Banded Hip Flexor Stretch", "isolation", "hip_mobility", "hip_flexors", "", "band", 0, 1, 1, 10, 25),
        ("Wall Slide", "isolation", "shoulder_mobility", "lower_traps,serratus_anterior", "", "bodyweight", 1, 1, 1, 10, 25),
        ("Cat-Cow", "isolation", "spinal_mobility", "erectors,core", "", "bodyweight", 1, 1, 1, 10, 25),
        ("World's Greatest Stretch", "compound", "hip_mobility", "hip_flexors,hamstrings,core", "shoulders", "bodyweight", 0, 1, 1, 10, 25),

        # === ADDITIONAL COMPOUND / SPECIALTY ===
        ("Landmine Press", "compound", "vertical_push", "anterior_deltoid,upper_chest", "triceps,core", "barbell", 0, 2, 2, 6, 20),
        ("Landmine Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid", "barbell", 0, 2, 2, 6, 20),
        ("Landmine Squat", "compound", "squat", "quads,glutes", "core", "barbell", 1, 2, 2, 6, 20),
        ("Dumbbell Pullover", "isolation", "vertical_pull", "lats,chest", "triceps_long_head,serratus_anterior", "dumbbell", 1, 1, 2, 8, 22),
        ("Cable Crossover", "isolation", "horizontal_push", "chest", "anterior_deltoid", "cable", 1, 1, 1, 8, 24),
        ("Hip Adduction Machine", "isolation", "hip_adduction", "adductors", "", "machine", 1, 1, 1, 10, 25),
        ("Leg Press (Single Leg)", "compound", "squat", "quads,glutes", "hamstrings", "machine", 0, 1, 2, 6, 22),
        ("Chest-Supported Dumbbell Row", "compound", "horizontal_pull", "lats,rhomboids,rear_deltoid", "biceps", "dumbbell", 1, 1, 2, 6, 22),
        ("Cable Lateral Raise (Behind)", "isolation", "lateral_raise", "lateral_deltoid", "", "cable", 0, 2, 1, 10, 25),
        ("Prone Y-T-W Raise", "isolation", "scapular_retraction", "lower_traps,rear_deltoid,rhomboids", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Sled Push", "compound", "loaded_carry", "quads,glutes,calves", "core", "other", 1, 2, 3, 8, 18),
        ("Sled Pull", "compound", "loaded_carry", "hamstrings,glutes,calves", "core,lats", "other", 1, 2, 3, 8, 18),

        # === ADDITIONAL EXERCISES TO REACH 250+ ===
        ("Deficit Push-Up", "compound", "horizontal_push", "chest,triceps", "anterior_deltoid", "bodyweight", 1, 2, 2, 8, 22),
        ("Feet-Elevated Push-Up", "compound", "horizontal_push", "upper_chest,triceps", "anterior_deltoid,core", "bodyweight", 1, 2, 2, 8, 22),
        ("Svend Press", "isolation", "horizontal_push", "chest", "anterior_deltoid", "other", 1, 1, 1, 10, 25),
        ("Decline Cable Fly", "isolation", "horizontal_push", "lower_chest", "anterior_deltoid", "cable", 1, 1, 1, 8, 24),
        ("Cable Curl (Single-Arm)", "isolation", "elbow_flexion", "biceps", "", "cable", 0, 1, 1, 10, 25),
        ("Zottman Curl", "isolation", "elbow_flexion", "biceps,brachioradialis", "forearms", "dumbbell", 1, 2, 1, 10, 22),
        ("Overhead Cable Curl", "isolation", "elbow_flexion", "biceps", "", "cable", 1, 1, 1, 10, 25),
        ("Cross-Body Hammer Curl", "isolation", "elbow_flexion", "brachialis,biceps", "", "dumbbell", 0, 1, 1, 10, 25),
        ("Tate Press", "isolation", "elbow_extension", "triceps", "chest", "dumbbell", 1, 2, 2, 8, 22),
        ("Overhead EZ-Bar Extension", "isolation", "elbow_extension", "triceps_long_head", "", "barbell", 1, 2, 2, 8, 22),
        ("Single-Arm Overhead Extension", "isolation", "elbow_extension", "triceps_long_head", "", "dumbbell", 0, 1, 1, 10, 25),
        ("Bench Dip", "compound", "vertical_push", "triceps", "chest,anterior_deltoid", "bodyweight", 1, 1, 2, 8, 22),
        ("Dumbbell Lateral Raise (Seated)", "isolation", "lateral_raise", "lateral_deltoid", "", "dumbbell", 1, 1, 1, 10, 25),
        ("Front Raise (Dumbbell)", "isolation", "shoulder_flexion", "anterior_deltoid", "", "dumbbell", 0, 1, 1, 10, 25),
        ("Front Raise (Cable)", "isolation", "shoulder_flexion", "anterior_deltoid", "", "cable", 0, 1, 1, 10, 25),
        ("Barbell Front Raise", "isolation", "shoulder_flexion", "anterior_deltoid", "", "barbell", 1, 1, 1, 10, 25),
        ("Machine Lateral Raise (Single Arm)", "isolation", "lateral_raise", "lateral_deltoid", "", "machine", 0, 1, 1, 10, 25),
        ("OAC ISO Hold (Top)", "isolation", "vertical_pull", "lats,biceps", "forearms", "bodyweight", 0, 5, 4, 4, 14),
        ("Typewriter Pull-Up", "compound", "vertical_pull", "lats,biceps", "rear_deltoid,core", "bodyweight", 0, 4, 4, 4, 14),
        ("Commando Pull-Up", "compound", "vertical_pull", "lats,biceps", "obliques,core", "bodyweight", 0, 3, 3, 6, 16),
        ("Negative Pull-Up", "compound", "vertical_pull", "lats,biceps", "rhomboids", "bodyweight", 1, 2, 3, 6, 20),
        ("Chest-to-Bar Pull-Up", "compound", "vertical_pull", "lats,biceps,rhomboids", "rear_deltoid", "bodyweight", 1, 3, 4, 6, 16),
        ("Supinated Barbell Row", "compound", "horizontal_pull", "lats,biceps,rhomboids", "rear_deltoid", "barbell", 1, 2, 3, 6, 20),
        ("Single-Arm Dumbbell Row", "compound", "horizontal_pull", "lats,rhomboids", "biceps,rear_deltoid", "dumbbell", 0, 1, 2, 6, 22),
        ("Pause Squat (Front)", "compound", "squat", "quads,core", "glutes", "barbell", 1, 3, 5, 6, 16),
        ("Hatfield Squat", "compound", "squat", "quads,glutes", "hamstrings", "barbell", 1, 2, 3, 6, 20),
        ("Chain Squat", "compound", "squat", "quads,glutes", "hamstrings,core", "barbell", 1, 3, 4, 6, 18),
        ("Band Squat", "compound", "squat", "quads,glutes", "hamstrings,core", "barbell", 1, 3, 4, 6, 18),
        ("Sumo Squat", "compound", "squat", "quads,glutes,adductors", "hamstrings", "barbell", 1, 2, 3, 6, 20),
        ("Hip Belt Squat", "compound", "squat", "quads,glutes", "core", "machine", 1, 1, 2, 6, 22),
        ("Jefferson Deadlift", "compound", "hip_hinge", "quads,glutes,hamstrings", "core,erectors", "barbell", 0, 4, 4, 4, 14),
        ("Reeves Deadlift", "compound", "hip_hinge", "hamstrings,glutes,forearms", "erectors,traps", "barbell", 1, 5, 4, 4, 12),
        ("Touch-and-Go Deadlift", "compound", "hip_hinge", "hamstrings,glutes,erectors", "quads,lats", "barbell", 1, 2, 4, 6, 18),
        ("Single-Leg Leg Press", "compound", "squat", "quads,glutes", "hamstrings", "machine", 0, 1, 2, 6, 22),
        ("Walking Lunge (Dumbbell)", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 1, 3, 6, 20),
        ("Curtsy Lunge", "compound", "lunge", "quads,glutes,adductors", "core", "dumbbell", 0, 2, 3, 6, 18),
        ("Reverse Lunge (Dumbbell)", "compound", "lunge", "quads,glutes", "hamstrings,core", "dumbbell", 0, 1, 3, 6, 20),
    ]

    db.executemany("""
        INSERT OR IGNORE INTO exercises
        (name, category, movement_pattern, primary_muscles, secondary_muscles,
         equipment, bilateral, complexity, fatigue_rating, mev_sets_per_week, mrv_sets_per_week)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, exercises)
    db.commit()
